### ISSUE TITLE
[FEAT] 홈 화면 아이 api 연결

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-projects-3rd/WeKids-FE#105]
# ⚙️ ISSUE

- 어떤 이슈인지 설명

# 📄 To-Do

- [ ] 부모 아이 저장하는거 locaStorage로 변경
- [ ] 아이 api 연결 tanstack 빼버려!
- [ ] 홈 화면 카드 바뀐거 디자인 변경
- [ ] 색상 local Storage에 저장
- [ ] link replach생각
- [ ] instance header적용
