### ISSUE TITLE
[FEAT] 홈 화면 작업

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-projects-3rd/WeKids-FE#12]
# ⚙️ ISSUE
- 홈 뷰 작업
<img src="https://github.com/user-attachments/assets/70721d00-302d-4226-9394-ce6545f1d7b9" width="300" height="500">

# 📄 To-Do
- [ ] 이미지 넣기(로고 이미지, 위비 이미지)
- [ ] 상단 해더 컴포넌트화 하기
- [ ] 아이콘 넣기 ( 알림, 사람, 복사)
- [ ] 네모네모 빔 만들기
