### ISSUE TITLE
[FEAT] 홈 화면 계좌 발급 바뀐 뷰 

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-projects-3rd/WeKids-FE#122]
# ⚙️ ISSUE
![image](https://github.com/user-attachments/assets/407bae41-73fa-4643-8617-74be609dc775)

# 📄 To-Do

- [x] 위의 꺼 구현할거임
- [x] 부모 입장에서 미션이 등록되지 않았을 때 보여주는 뷰
- [x] 아이 입장에서 미션이 등록되지 않았을 떄 뷰
- [x] 계좌 가져와주세요 카드
- [ ] 회원가입 요청
- [x] 체크카드 발급하기
- [ ] 미션클릭 카드
- [ ] userType zustad 장기저장 되게 바꾸기
