### ISSUE TITLE
[FIX] Design API error 수정

### ISSUE THREAD

**Issue by AnChanUng** [woorifisa-projects-3rd/WeKids-FE#126]
# ⚙️ ISSUE

- 어떤 이슈인지 설명
카드 커스텀 뷰 error 수정

# 📄 To-Do

- [x] 디자인 생성 API 수정
- [x] 디자인 조회 API 수정
- [x] 각종 api error 수정
