### ISSUE TITLE
[REFACTOR] 모달 컴포넌트 수정

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-projects-3rd/WeKids-FE#15]
# ⚙️ ISSUE
- 모달 컴포넌트 닫기 이벤트 수정
- 키패드 일부 수정

# 📄 To-Do
- [x] 모달창 외부를 누르면 닫는 기능
- [x] x버튼을 외부에서 선택가능한 기능
- [x] 키패드 버튼 개개인 값 변경이 아닌 전체 크기로 변경
