### ISSUE TITLE
[REFACT] 패키지 구조 수정 

### ISSUE THREAD

**Issue by dpdms529** [woorifisa-projects-3rd/WeKids-FE#24]
# ⚙️ ISSUE
- 패키지 구조 수정 

# 📄 To-Do
- [x] 라우팅 구조 수정 - @dpdms529 
- [x] 공통 컴포넌트 수정 - @dpdms529 
- [x] js -> jsx 수정
- [x] 패키지랑 일반 JS 파일은 카멜케이스로, 라우팅 패키지는 케밥케이스로, 컴포넌트는 파스칼케이스 수정
- [x] 상태관리도 어떻게 할지 결정 후 수정 - @dpdms529 
- [x] constants 패키지 생성 - @jabin1221 
- [x] .jpg 삭제 - @jabin1221 
- [x] 공통 색상 적용 - @jabin1221 
- [x] 아이콘 파일명 뒤에 Icon 붙이기 - @jabin1221
