### ISSUE TITLE
[REFACT] 미처 수정하지 못한 이슈들

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-projects-3rd/WeKids-FE#28]
# ⚙️ ISSUE
- 어떤 이슈인지 설명

# 📄 To-Do
- [x] 이체 뷰, 자식계좌 선택 리스트 뷰 bg white로 바꾸기
- [x] 이체하기뷰에서 +1, +10 이런 버튼 색 다시 맞추기
- [x] 색이랑, 폰트 각자 맡은 뷰 피그마에 있는 걸로 바꾸기
- [x] 상대경로 절대경로로 바꾸기
- [ ] hook 빼기
 ```
useEffect(() => {
    if (isShaking) {
      const timeout = setTimeout(() => {
        setIsShaking(false);
      }, 500);
      return () => clearTimeout(timeout);
    }
  }, [isShaking]);
```
- [ ] routing 이상한거 고치고
> - [ ] 계좌 조회뷰에서 뒤로가기 클릭시 홈으로 이동
> - [ ] 자식뷰에서 이체하기 클릭했을 때 자식선택 리스트가 아니라 이체뷰로 바로 넘어가기
- [ ] constants에 들어가는 상수객체 네이밍 정하기 (RangeEnum, urlPath, characterInfoMap)
- [x] Component ->component로 수정
