### ISSUE TITLE
[REFACT] 홈 화면

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-projects-3rd/WeKids-FE#29]
# ⚙️ ISSUE
- 미처 수정하지 못한 이슈들 중에서 홈 화면에 해당하는거 수정할 것 입니다.

# 📄 To-Do
- [x] 하드코딩 되어 있는 색상 수정하기
- [x] 폰트 figma에 있는거대로 수정
- [x] 상대경로 절대경로로 바꾸기
- [x] toast 사용하기
![image](https://github.com/user-attachments/assets/9c39702e-984e-4080-8180-d55a7bf9e411)
