### ISSUE TITLE
[FEAT] 본인 개인정보 작성 뷰

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-projects-3rd/WeKids-FE#37]
# ⚙️ ISSUE
- 본인 개인정보 작성 뷰

# 📄 To-Do
- [x] 이메일이나 이름을 입력하는 textfield 생성
- [x] 약관동의를 모두 해야 다음 버튼 색변경 및 활성화
- [x] 약관동의를 누르면 세부 약관설명이 나오는 모달
- [x] 휴대폰 인증
