### ISSUE TITLE
[FEAT] 2차 공통 컴포넌트 작업(모달, 일부 상자)

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-projects-3rd/WeKids-FE#45]
# ⚙️ ISSUE
- 2차 공통컴포넌트 작업

# 📄 To-Do
- [x] 가운데 뜨는 모달창 구현
- [x] 캐릭터 카드 구현
- [x] 선택 상자 구현
