### ISSUE TITLE
[FEAT] 홈뷰에서 부모/자녀의 뷰 분기 처리

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-projects-3rd/WeKids-FE#60]
# ⚙️ ISSUE
### 부모입장에서 자식의 카드가 없을 때
<img src="https://github.com/user-attachments/assets/d6fa4ed9-557f-4b89-a7f3-b32b2dd0e481" width="200" height="400"/>

### 자식입장에서 카드가 없을 때
<img src="https://github.com/user-attachments/assets/ce421c61-6840-42b3-a544-51e6a5d8f7f9" width="200" height="400"/>

### Header 알림 없을 때
<img src="https://github.com/user-attachments/assets/042c5d39-41f9-4b83-9c79-69178481153a" width="600" height="200"/>

### Header 알림 있을 때
![image](https://github.com/user-attachments/assets/8f5b5d4b-cb9c-4d72-a3c7-0681a1be6178)
### 등록된 계좌가 없을 때
![image](https://github.com/user-attachments/assets/5c942f21-1e02-4a0a-a392-f28f895f7e89)

# 📄 To-Do
- [ ] 위의 이슈에 맞게끔 홈뷰에서 분기처리
- [ ] 자녀 입장의 뷰 일때 프로필 안보이게 분기 처리
- [ ] transaction history 자녀인 경우에는 이체/가져오기 안보이게 하기
