### ISSUE TITLE
[REFACT] 뷰 병합

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-projects-3rd/WeKids-FE#76]
# ⚙️ ISSUE

- 뷰 병합

# 📄 To-Do

- [x] 회원가입 페이지(select/self) zustand 적용
- [x] 회원가입 페이지 버튼 오류 수정
- [x] 카드 비밀번호 4자리 입력되는 뷰 만들기 -> 완료 클릭 시 발급신청 완료 뷰로 이동 생각하면서 작업해주세용!
- [x] 비밀번호 주의 경고창 왜 뜨는지 알아보기
- [ ] 주민번호 같은 경우 "숫자를 다 입력해야지만 됩니다" 이런식의 왜 안되는지에 대한 설명이 필요하다고 생각합니당
