### ISSUE TITLE
[FEAT] 송금 화면 뷰

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-projects-3rd/WeKids-FE#8]
# ⚙️ ISSUE
- 송금 화면 뷰 구현
![image](https://github.com/user-attachments/assets/26c7a463-ade5-48db-8a61-3488cd707127)
![image](https://github.com/user-attachments/assets/d23be9c5-8137-4e73-9e2e-2b48195927a5)

# 📄 To-Do
- [x] 상단에 뒤로가는 버튼 컴포넌트 구현
- [x] 상단의 이름을 누를 경우 다른 이름 선택 가능하게 구현
- [x] 다음 버튼을 눌렀을 경우 뜨는 모달창 구현
- [x] 키패드를 누를 경우 화면에 금액이 뜨도록 구현
