### ISSUE TITLE
[FEAT] 디자인 api

### ISSUE THREAD

**Issue by AnChanUng** [woorifisa-projects-3rd/WeKids-FE#99]
# ⚙️ ISSUE

- 카드 발급 디자인 선택 뷰 (생성) - /design
- 간편 비밀번호 등록 뷰 - /parent/card/apply/password
- 부모 동의 대기 뷰 - /child/card/complete

![image](https://github.com/user-attachments/assets/f8e4306d-d822-44d5-96d0-74654ba5c40b)

----------------------------------------------------
완료한 page 목록

디자인 선택 뷰
![image](https://github.com/user-attachments/assets/f3347a6e-2019-4e86-b7ee-a37d0431a977)
간편 비밀번호 등록 뷰 (4자리 비밀번호)
![image](https://github.com/user-attachments/assets/2b09c190-fae6-4560-bb0c-3b86f7fdc8da)

# 📄 To-Do

- [x] 카드 발급 선택 뷰 (생성)
- [x] 간편 비밀번호 등록 (4자리 비밀번호) - (서버API /api/v1/accounts/cards/issue 계좌생성/카드발급)
- [x] 부모 동의 대기 뷰 - (서버API 디자인 조회)
